# Generated by Django 5.2.8 on 2025-11-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercontribution',
            name='reference',
            field=models.CharField(blank=True, help_text='Receipt or transaction reference', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='due_date',
            field=models.DateField(blank=True, help_text='For Annual and Once-off contributions', null=True),
        ),
    ]
