# Generated by Django 5.2.8 on 2025-11-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_membercontribution_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontribution',
            name='is_paid',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('NOT PAID', 'Not paid'), ('CANCELLED', 'Cancelled')], default='NOT PAID', max_length=100),
        ),
    ]
