# Generated by Django 5.2.8 on 2025-11-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_payment_checkout_id_payment_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_first_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_last_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='client_phone',
        ),
    ]
