# Generated by Django 5.2.8 on 2025-11-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_role'),
        ('contributions', '0005_remove_payment_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_contribution_types', to='accounts.family'),
        ),
        migrations.AddField(
            model_name='contributiontype',
            name='scope',
            field=models.CharField(choices=[('clan', 'Entire Clan'), ('family_leaders', 'Family Leaders'), ('family', 'Specific Family'), ('Executives', 'Executives')], default='clan', max_length=20),
        ),
    ]
