# Generated by Django 5.2.8 on 2025-11-16 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_contributiontype_family_contributiontype_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_approved',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Payment verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin/treasurer who verified/approved payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_verified_date',
            field=models.DateTimeField(blank=True, help_text='When payment was verified', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, help_text='Upload bank statement, screenshot, or receipt image', null=True, upload_to='payments/proof/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.CharField(blank=True, help_text='Receipt number from bank/payment provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if payment was rejected', null=True),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='scope',
            field=models.CharField(choices=[('clan', 'Entire Clan'), ('family_leaders', 'Family Leaders'), ('family', 'Specific Family'), ('executives', 'Executives')], default='clan', max_length=20),
        ),
        migrations.AlterField(
            model_name='membercontribution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='membercontribution',
            name='is_paid',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('NOT_PAID', 'Not paid'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_PAID', 'PARTIALLY PAID')], db_index=True, default='NOT_PAID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Deposit'), ('mobile', 'Yoco Mobile Payment'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(help_text='Treasurer or admin who logged this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account', '-payment_date'], name='contributio_account_0c4a85_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_approved', 'payment_date'], name='contributio_is_appr_e87728_idx'),
        ),
    ]
