# Generated by Django 5.2.8 on 2025-11-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_payment_is_approved_payment_payment_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
