# Generated by Django 5.2.8 on 2025-11-08 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='End date and time of the meeting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(help_text='Start date and time of the meeting'),
        ),
    ]
