# Generated by Django 5.2.8 on 2025-11-16 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_meeting_meeting_end_date_alter_meeting_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clandocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
