# Generated by Django 5.2.8 on 2025-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(help_text='Enter family name e.g Dladla Family', max_length=300, unique=True),
        ),
    ]
