# Generated by Django 5.2.8 on 2025-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('KGOSANA', 'Kgosana'), ('CHAIRPERSON', 'Chairperson'), ('FAMILY LEADER', 'Family leader'), ('MEMBER', 'Member'), ('DEP-CHAIRPERSON', 'Deputy Chairperson'), ('SECRETARY', 'Secretary'), ('DEP SECRETARY', 'Deputy Secretary'), ('TREASURER', 'Treasurer')], default='MEMBER', max_length=100),
        ),
    ]
