# Generated by Django 5.2.8 on 2025-11-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Should be approved by executives'),
        ),
        migrations.AddField(
            model_name='family',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Should be approved by executives'),
        ),
    ]
