# Generated by Django 5.2.8 on 2025-11-16 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_is_approved_family_is_approved'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('KGOSANA', 'Kgosana'), ('CLAN_CHAIRPERSON', 'Chairperson'), ('FAMILY_LEADER', 'Family leader'), ('MEMBER', 'Member'), ('DEP_CHAIRPERSON', 'Deputy Chairperson'), ('SECRETARY', 'Secretary'), ('DEP_SECRETARY', 'Deputy Secretary'), ('TREASURER', 'Treasurer')], default='MEMBER', max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_approved'], name='accounts_ac_is_appr_dd123d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['family'], name='accounts_ac_family__c4b227_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_approved'], name='accounts_fa_is_appr_f5e68a_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['slug'], name='accounts_fa_slug_8bd0d8_idx'),
        ),
    ]
